### PR TITLE
Fix issue 8

### PR DESCRIPTION
**Pull request by cappslock**
This is a proposed and tested fix for issue 8: https://github.com/mirhampt/node-recaptcha/issues/8

### CODE REVIEW

**Comment by xzela** [comment]
+1

**Comment by germanattanasio** [comment]
:+1:

**Comment by cappslock** [comment]
2 years and going strong, I wouldn't hold my breath :)

**Comment by germanattanasio** [comment]
Haha I will probably implement my own node-recaptcha. I don't like the license he is using

**Comment by germanattanasio** [comment]
Oh I just saw that is MIT. Never mind

**Comment by germanattanasio** [comment]
hello?

**Comment by germanattanasio** [comment]
5 years waiting here

**Comment by germanattanasio** [comment]
6 years and counting

**Pull request closed without merging**
